formatter: "markdown" # this is required

version: "0.16.0"

header-from: "main.tf"
footer-from: ""

recursive:
  enabled: false
  path: ./

sections:
  hide: []
  show:
  - providers
  - inputs
  - outputs

content: ""

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
